# Generated by Django 3.1.1 on 2020-09-26 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_piece'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piece',
            name='artistId',
        ),
    ]
