# Generated by Django 3.1.1 on 2020-09-26 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_piece_artistid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isOpened', models.BooleanField(default=False)),
                ('dislcaimer', models.CharField(default=None, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(default=None, max_length=10)),
                ('website', models.CharField(default=None, max_length=50)),
                ('store', models.CharField(default=None, max_length=50)),
                ('instagram', models.CharField(default=None, max_length=50)),
                ('facebook', models.CharField(default=None, max_length=50)),
                ('twitter', models.CharField(default=None, max_length=50)),
                ('etsy', models.CharField(default=None, max_length=50)),
                ('other', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='artist',
            name='genre',
        ),
        migrations.AlterField(
            model_name='piece',
            name='description',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='piece',
            name='materials_used',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='piece',
            name='media',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='piece',
            name='price',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='piece',
            name='title',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
