# Generated by Django 3.1.1 on 2020-09-26 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200926_0423'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Piece',
        ),
    ]
