# Generated by Django 3.1.1 on 2020-09-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_artist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='bg_color',
            field=models.CharField(default='white', max_length=50),
        ),
    ]
