# Generated by Django 3.1.1 on 2020-09-28 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20200927_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commision',
            old_name='user',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='user',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='exhibit',
            old_name='user',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='user',
            new_name='artist',
        ),
    ]
