# Generated by Django 3.1.1 on 2020-09-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_artist_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='tags',
        ),
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(to='main_app.Tag'),
        ),
    ]
