# Generated by Django 3.1.1 on 2020-09-28 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_auto_20200928_0217'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='PhotoExhibit',
        ),
        migrations.RenameModel(
            old_name='Exhibit',
            new_name='TextExhibit',
        ),
    ]
