# Generated by Django 3.1.1 on 2020-09-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_observer'),
    ]

    operations = [
        migrations.AddField(
            model_name='textexhibit',
            name='tags',
            field=models.ManyToManyField(to='main_app.Tag'),
        ),
    ]
