# Generated by Django 3.1.1 on 2020-09-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_textexhibit_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoexhibit',
            name='description',
            field=models.CharField(default='write it out here', max_length=100),
        ),
        migrations.AddField(
            model_name='photoexhibit',
            name='materials_used',
            field=models.CharField(default='materials', max_length=100),
        ),
    ]
