# Generated by Django 3.1.1 on 2020-09-29 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_auto_20200929_1754'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commision',
            new_name='Commission',
        ),
    ]
