# Generated by Django 3.1.1 on 2020-09-29 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_auto_20200929_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='id',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='id',
        ),
        migrations.AlterField(
            model_name='commission',
            name='artist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main_app.artist'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='artist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main_app.artist'),
        ),
    ]
