# Generated by Django 3.1.1 on 2020-09-29 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_auto_20200929_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commission',
            old_name='dislcaimer',
            new_name='disclaimer',
        ),
    ]
