# Generated by Django 3.1.1 on 2020-09-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_auto_20200930_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='instagram',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='store',
            field=models.CharField(default='', max_length=50),
        ),
    ]
