# Generated by Django 3.1.1 on 2020-09-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0036_auto_20200930_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoexhibit',
            name='for_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='textexhibit',
            name='for_sale',
            field=models.BooleanField(default=False),
        ),
    ]
