# Generated by Django 3.1.1 on 2020-10-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0039_artist_as_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='iconphoto',
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.IntegerField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='photoexhibit',
            name='description',
            field=models.TextField(default='write it out here', max_length=1000),
        ),
        migrations.AlterField(
            model_name='photoexhibit',
            name='title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Title (optional)'),
        ),
        migrations.AlterField(
            model_name='textexhibit',
            name='title',
            field=models.CharField(default='title', max_length=250),
        ),
    ]
