# Generated by Django 3.1.1 on 2020-10-09 21:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0042_auto_20201009_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='textexhibit',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
