# Generated by Django 3.1.1 on 2020-10-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0043_textexhibit_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoexhibit',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='photoexhibit',
            name='link_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='textexhibit',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='textexhibit',
            name='link_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
