# Generated by Django 3.1.1 on 2020-10-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0044_auto_20201009_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='medium',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='other_description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='other_two',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='other_two_description',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
