# Generated by Django 3.1.1 on 2020-10-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0045_auto_20201011_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='bandcamp',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='soundcloud',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='spotify',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
