# Generated by Django 3.1.1 on 2020-10-12 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0046_auto_20201011_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoexhibit',
            name='link_title',
        ),
    ]
